# Generated by Django 3.2.12 on 2023-03-24 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20230325_0317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactModel',
            new_name='ContactlistModel',
        ),
    ]
